DROP TABLE IF EXISTS book;

CREATE TABLE book (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  `name` TEXT NOT NULL DEFAULT '',
  cover TEXT NOT NULL DEFAULT '',
  original_name TEXT NOT NULL DEFAULT '',
  author TEXT NOT NULL DEFAULT '',
  press TEXT NOT NULL DEFAULT '',
  translator TEXT NOT NULL DEFAULT '',
  publication_time TEXT NOT NULL DEFAULT '',
  pricing TEXT NOT NULL DEFAULT '',
  isbn TEXT NOT NULL DEFAULT '',
  intro TEXT NOT NULL DEFAULT '',
  score TEXT NOT NULL DEFAULT '',
  create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);